import { useQuery } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { Download } from "lucide-react";
import { toast } from "sonner";
import { Brand } from "@/components/Brand";
import { PageHeader } from "@/components/PageHeader";
import { ComplianceBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { AppLayout } from "@/layouts/AppLayout";
import { downloadReport, getReport } from "@/services/reportService";

export const Route = createFileRoute("/reports")({
  head: () => ({
    meta: [
      { title: "Compliance Assessment Report — ProtoMind" },
      {
        name: "description",
        content:
          "Tender compliance assessment report with executive summary, requirement results, evidence and risk assessment.",
      },
      { property: "og:title", content: "Compliance Assessment Report — ProtoMind" },
      {
        property: "og:description",
        content: "Executive summary, requirement results, evidence and risk assessment.",
      },
    ],
  }),
  component: ReportsPage,
});

function ReportsPage() {
  const { data: report } = useQuery({
    queryKey: ["report", "demo-analysis"],
    queryFn: () => getReport("demo-analysis"),
  });

  if (!report) {
    return (
      <AppLayout>
        <p className="text-sm text-muted-foreground">Preparing report…</p>
      </AppLayout>
    );
  }

  return (
    <AppLayout>
      <PageHeader
        eyebrow={`Report ${report.id}`}
        title="Compliance Report"
        subtitle="Generated for procurement officer review and sign-off."
        actions={
          <Button
            onClick={async () => {
              await downloadReport(report.analysisId);
              toast.success("Report downloaded.");
            }}
          >
            <Download className="h-4 w-4" />
            Download PDF Report
          </Button>
        }
      />

      <article className="card-surface mx-auto max-w-4xl p-10">
        <header className="border-b border-border pb-6">
          <Brand size="sm" />
          <h2 className="mt-4 text-xl font-semibold text-foreground">
            Tender Compliance Assessment Report
          </h2>
          <dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
            <div>
              <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                Tender
              </dt>
              <dd className="num mt-1 text-sm font-medium text-foreground">
                {report.tenderNumber}
              </dd>
            </div>
            <div>
              <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                Bidder
              </dt>
              <dd className="mt-1 text-sm font-medium text-foreground">{report.bidder}</dd>
            </div>
            <div>
              <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                Analysis Date
              </dt>
              <dd className="mt-1 text-sm font-medium text-foreground">
                {report.analysisDate}
              </dd>
            </div>
            <div>
              <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                Overall Status
              </dt>
              <dd className="mt-1">
                <ComplianceBadge status={report.overallStatus} />
              </dd>
            </div>
            <div>
              <dt className="text-xs uppercase tracking-wide text-muted-foreground">
                Risk Score
              </dt>
              <dd className="num mt-1 text-sm font-medium text-foreground">
                {report.riskScore}/100
              </dd>
            </div>
          </dl>
        </header>

        <div className="divide-y divide-border">
          {report.sections.map((section, index) => (
            <section key={section.title} className="py-6">
              <h3 className="text-sm font-semibold uppercase tracking-wide text-foreground">
                <span className="num mr-2 text-muted-foreground">
                  {String(index + 1).padStart(2, "0")}
                </span>
                {section.title}
              </h3>
              <div className="mt-3 space-y-2">
                {section.body.map((paragraph) => (
                  <p
                    key={paragraph}
                    className="text-sm leading-relaxed text-muted-foreground"
                  >
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        <footer className="border-t border-border pt-6 text-xs text-muted-foreground">
          Report {report.id} · Generated by ProtoMind in Demo Mode · AI assists. Rules
          validate. Human decides.
        </footer>
      </article>
    </AppLayout>
  );
}
